# Generated by Django 5.0.6 on 2025-07-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='outcomeitem',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
