# Generated by Django 5.0.6 on 2025-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_income_status_alter_incomeitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('active', 'Активный'), ('finished', 'Закончен'), ('cancelled', 'Отменен')], default='pending', max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
