# Generated by Django 5.0.6 on 2025-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_incomeitem_comment_alter_incomeitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
