# Generated by Django 5.0.6 on 2025-07-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_warehouseproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, null=True, verbose_name='Код продукта'),
        ),
    ]
