# Generated by Django 5.0.6 on 2025-07-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomeitem',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.outcome', verbose_name='Расход'),
        ),
    ]
