# Generated by Django 5.0.6 on 2025-07-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_outcomeitem_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='reason',
            field=models.TextField(null=True, verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('collected', 'Собрано'), ('sent', 'Отправлено'), ('received', 'Получено'), ('finished', 'Закончено')], default='pending', max_length=255, verbose_name='Статус')),
                ('comment', models.TextField(verbose_name='Коммент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('warehouse_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_from', to='api.warehouse', verbose_name='С какого склада')),
                ('warehouse_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_to', to='api.warehouse', verbose_name='На какой склад')),
            ],
            options={
                'verbose_name': 'Пермещение',
                'verbose_name_plural': 'Перемещения',
            },
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('comment', models.TextField(verbose_name='Коммент')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.movement', verbose_name='Перемещение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Элемент перемещения',
                'verbose_name_plural': 'Элементы перемещения',
            },
        ),
    ]
