# Generated by Django 5.0.6 on 2025-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_income_total_amount_alter_outcome_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Общая сумма'),
        ),
    ]
