# Generated by Django 5.0.6 on 2025-07-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeitem',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='outcomeitem',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='unit_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Шт.'), ('kg', 'Кг.')], default='pcs', max_length=255, verbose_name='Ед. изм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
