# Generated by Django 5.0.6 on 2025-07-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_incomeitem_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
