# Generated by Django 5.0.6 on 2025-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_report_reportitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('collected', 'Собрано'), ('sent', 'Отправлено'), ('received', 'Получено'), ('finished', 'Закончено'), ('cancelled', 'Отменено'), ('confirmed_cancel', 'Отмена подтверждена')], default='pending', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('collected', 'Собрано'), ('delivering', 'Доставляется'), ('delivered', 'Доставлено'), ('sent', 'Отправлено'), ('cancelled', 'Отменено')], default='pending', max_length=255, verbose_name='Статус'),
        ),
    ]
