# Generated by Django 5.0.6 on 2025-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_income_total_amount_alter_outcome_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='reason',
            field=models.CharField(choices=[('order', 'Заказ'), ('movement', 'Перемещение'), ('income', 'Приход')], default='order', max_length=255, verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='income',
            name='reason_id',
            field=models.IntegerField(default=0, verbose_name='Айди причины'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='reason_id',
            field=models.IntegerField(default=0, verbose_name='Айди причины'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='reason',
            field=models.CharField(choices=[('order', 'Заказ'), ('movement', 'Перемещение'), ('outcome', 'Расход')], default='order', max_length=255, verbose_name='Причина'),
        ),
    ]
