# Generated by Django 5.0.6 on 2025-10-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_income_reason_income_reason_id_outcome_reason_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='banner', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('disabled', 'Отключен')], default='active', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена со скидкой')),
                ('photo', models.ImageField(upload_to='catalog', verbose_name='Фото')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('disabled', 'Отключен')], default='active', max_length=255, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
    ]
