# Generated by Django 5.0.6 on 2025-10-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_banner_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='movementitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
    ]
