# Generated by Django 5.0.6 on 2025-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('provider', 'Провайдер'), ('admin', 'Админ'), ('dealer', 'Дилер')], default='provider', max_length=255),
        ),
    ]
