# Generated by Django 5.0.6 on 2025-10-19 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('disabled', 'Заблокирован')], default='active', max_length=255, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Баланс пользователя',
                'verbose_name_plural': 'Балансы пользователей',
            },
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(max_length=255, verbose_name='Тип операции')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('finished', 'Закончено')], default='active', max_length=255, verbose_name='Статус')),
                ('comment', models.TextField(null=True, verbose_name='Коммент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userbalance', verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Операции по счету',
                'verbose_name_plural': 'Операции по счетам',
            },
        ),
    ]
