# Generated by Django 5.0.6 on 2025-10-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userbalance_balancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
