# Generated by Django 5.0.6 on 2025-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_balancehistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='history_type',
            field=models.CharField(choices=[('income', 'Пополнение'), ('outcome', 'Расход'), ('withdraw', 'Вывод')], default='income', max_length=255, verbose_name='Тип операции'),
        ),
    ]
