# Generated by Django 5.0.6 on 2025-10-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_balancehistory_history_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('provider', 'Провайдер'), ('admin', 'Админ'), ('dealer', 'Дилер'), ('warehouse', 'Складовщик')], default='provider', max_length=255),
        ),
    ]
